BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `defined` (
	`part_of_speech`	text NOT NULL,
	`definition`	text,
	`term`	text,
	PRIMARY KEY(`part_of_speech`,`term`)
);
INSERT INTO `defined` (part_of_speech,definition,term) VALUES ('Adjective','especially of petals or leaves in bud; having margins rolled inward, (of some shells','INVOLUTE'),
 ('Noun','ornament consisting of a curve on a plane that winds around a center with an increasing distance from the center, a structure consisting of something wound in a continuous series of loops','VOLUTE'),
 ('Adjective','in the shape of a coil','VOLUTE'),
 ('Adjective','of or relating to or near the groin','INGUINAL'),
 ('Noun','a musical form that is often the last movement of a sonata','RONDO'),
 ('Adverb','in a series; point by point','SERIATIM'),
 ('Noun','a socially awkward or tactless act','SOLECISM'),
 ('Adjective','effusively or insincerely emotional','BATHETIC'),
 ('Noun','anxious embarrassment','DISCOMFITURE'),
 ('Adverb','in a sedulous manner','SEDULOUSLY'),
 ('Noun','substituting the name of an attribute or feature for the name of the thing itself (as in `they counted heads','METONYMY'),
 ('Noun','someone (usually maleficent, "the musician in a novel by George du Maurier who controls Trilbys singing hypnotically','SVENGALI'),
 ('Noun','(nautical, the act of sailing close to the wind','LUFF'),
 ('Verb','sail close to the wind, flap when the wind is blowing equally on both sides','LUFF'),
 ('Noun','a wedding hymn','HYMENEAL'),
 ('Adjective','of or relating to a wedding or marriage','HYMENEAL'),
 ('Verb','cause to ripen and discharge pus, ripen and generate pus','SUPPURATE'),
 ('Noun','burial garment in which a corpse is wrapped','CEREMENT'),
 ('Verb','become productive or fruitful, make productive or fruitful, bear fruit','FRUCTIFY'),
 ('Noun','a state of motor and mental inactivity with a partial suspension of sensibility, inactivity resulting from lethargy and lack of vigor or energy','TORPOR'),
 ('Adjective','lacking physical strength or vigor','IMPUISSANT'),
 ('Noun','the commonest type of solidified lava; a dense dark grey fine-grained igneous rock that is composed chiefly of plagioclase feldspar and pyroxene','BASALT'),
 ('Noun','a green variety of chalcedony valued as a gemstone','CHRYSOPRASE'),
 ('Noun','gay or light-hearted recreational activity for diversion or amusement','GAMBOL'),
 ('Verb','play boisterously','GAMBOL'),
 ('Noun','a mass of hay piled up in a barn for preservation, a loft in a barn where hay is stored','HAYMOW'),
 ('Noun','(formerly','LEVANTINE'),
 ('Adjective','of or relating to the Levant or its inhabitants','LEVANTINE'),
 ('Noun','an event that is experienced as indicating important things to come','AUGURY'),
 ('Noun','highly decorated earthenware with a glaze of tin oxide','MAJOLICA'),
 ('Noun','a strip of land projecting into a body of water','NESS'),
 ('Noun','a milky or greyish translucent to transparent quartz','CHALCEDONY'),
 ('Adjective','of windows; divided by vertical bars or piers usually of stone','MULLIONED'),
 ('Noun','coil in which voltage is induced by motion through a magnetic field','ARMATURE'),
 ('Noun','a basin for washing the hands (`wash-hand basin is a British expression','LAVABO'),
 ('Noun','any of various rotating shafts that serve as axes for larger rotating parts','MANDREL'),
 ('Noun','a water wheel with buckets attached to the rim; used to raise water for transfer to an irrigation channel','NORIA'),
 ('Noun','a puzzle where you decode a message consisting of pictures representing syllables and words','REBUS'),
 ('Noun','domesticated ox having a humped back and long horns and a large dewlap; used chiefly as a draft animal in India and east Asia','ZEBU'),
 ('Noun','the highest part of the back at the base of the neck of various animals especially draft animals','WITHERS'),
 ('Noun','a whistling sound when breathing (usually heard on inspiration','STRIDOR'),
 ('Noun','any igneous rock with crystals embedded in a finer groundmass of minerals','PORPHYRY'),
 ('Noun','a triangular gable between a horizontal entablature and a sloping roof','PEDIMENT'),
 ('Noun','a railing at the side of a staircase or balcony to prevent people from falling','BALUSTRADE'),
 ('Noun','small deciduous tree of southern Africa having edible fruit, small deciduous Eurasian tree cultivated for its fruit that resemble crab apples, a South African globular fruit with brown leathery skin and pithy flesh having a sweet-acid taste, crabapple-like fruit used for preserves','MEDLAR'),
 ('Noun','a kind of hemp obtained from the abaca plant in the Philippines, Philippine banana tree having leafstalks that yield Manila hemp used for rope and paper etc','ABACA'),
 ('Noun','a woman who tells fortunes, (ancient Rome','SIBYL'),
 ('Noun','a woman slave in a harem','ODALISQUE'),
 ('Noun','either of the horny front wings in beetles and some other insects which cover and protect the functional hind wings','ELYTRON'),
 ('Noun','hospital for persons with infectious diseases (especially leprosy, a small locker at the stern of a boat or between decks of a ship','LAZARETTO'),
 ('Noun','the act of stripping and taking by force','SPOLIATION'),
 ('Adjective','full in all respects','PLENARY'),
 ('Noun','a small natural hill','HUMMOCK'),
 ('Noun','United States tennis player who won womens singles titles in the United States and at Wimbledon (born in 1954','EVERT'),
 ('Verb','turn inside out; turn the inner surface of outward','EVERT'),
 ('Noun','last of the seven canonical hours just before retiring','COMPLINE'),
 ('Noun','(prosody','ALEXANDRINE'),
 ('Noun','a rectangular column that usually projects about a third of its width from the wall to which it is attached','PILASTER'),
 ('Adjective','hard to deal with; especially causing pain or embarrassment, or embarrassing or difficult, causing to feel shame or chagrin or vexation','EMBARRASSING'),
 ('Noun','French painter noted for his paintings of Parisian street scenes (1883-1955','UTRILLO'),
 ('Noun','a piece of metal covered by leather with a flexible handle; used for hitting people','COSH'),
 ('Verb','hit with a cosh, usually on the head','COSH'),
 ('Noun','someone new to a field or activity','TYRO'),
 ('Verb','make peace with','PROPITIATE'),
 ('Adjective','having the power to prevent evil or bad luck','APOTROPAIC'),
 ('Adjective','offensively self-assertive','BUMPTIOUS'),
 ('Verb','be opposite to; of angles and sides, in geometry','SUBTEND'),
 ('Noun','decoration consisting of an open pattern of interlacing ribs','TRACERY'),
 ('Noun','the month following August and preceding October, people descended from a common ancestor','SEPT'),
 ('Noun','a closed litter carried on the shoulders of four bearers','PALANQUIN'),
 ('Adjective','powerful','PUISSANT'),
 ('Noun','a thief who steals from someone by threatening violence','ROBBER'),
 ('Noun','someone who guards prisoners','GAOLER'),
 ('Adverb','in a timorous and trepid manner','TIMOROUSLY'),
 ('Noun','flesh of quail; suitable for roasting or broiling if young; otherwise must be braised, small gallinaceous game birds','QUAIL'),
 ('Verb','draw back, as with fear or pain','QUAIL'),
 ('Noun','an enclosed compartment from which a vessel can be navigated','WHEELHOUSE'),
 ('Noun','a short sleeveless outer tunic emblazoned with a coat of arms; worn by a knight over his armor or by a herald','TABARD'),
 ('Noun','alternative terms for gallows','GIBBET'),
 ('Verb','hang on an execution instrument, expose to ridicule or public scorn','GIBBET'),
 ('Noun','shade within clear boundaries, an unilluminated area, something existing in perception only, a premonition of something adverse, an indication that something has been present, refuge from danger or observation, a dominating and pervasive presence, a spy employed to follow someone and report their movements, an inseparable companion','SHADOW'),
 ('Verb','follow, usually without the persons knowledge", cast a shadow over, make appear small by comparison','SHADOW'),
 ('Noun','European bison having a smaller and higher head than the North American bison, large recently extinct long-horned European wild ox; considered one of the ancestors of domestic cattle','AUROCHS'),
 ('Noun','a French verse form of 10 or 13 lines running on two rhymes; the opening phrase is repeated as the refrain of the second and third stanzas','RONDEL'),
 ('Noun','surface layer of ground containing a mat of grass and grass roots','SWARD'),
 ('Noun','a heavy silk fabric (often woven with silver or gold threads','SAMITE'),
 ('Noun','a pen for sheep','SHEEPFOLD'),
 ('Noun','an ancient Prakrit language (derived from Sanskrit','PALI'),
 ('Verb','make a crackling sound','CREPITATE'),
 ('Adjective','of or belonging to or suitable for a duke','DUCAL'),
 ('Noun','an evasion of the point of an argument by raising irrelevant distinctions or objections','CAVIL'),
 ('Verb','raise trivial objections','CAVIL'),
 ('Noun','a short stout club used primarily by policemen','TRUNCHEON'),
 ('Noun','a boy who submits to a sexual relationship with a man','CATAMITE'),
 ('Noun','economic independence as a national policy','AUTARKY'),
 ('Verb','speak unfavorably about','TRADUCE'),
 ('Noun','son of Apollo; a hero and the Roman god of medicine and healing; his daughters were Hygeia and Panacea','ASCLEPIUS'),
 ('Noun','a fold of skin covering the tip of the clitoris, a fold of skin covering the tip of the penis','PREPUCE'),
 ('Verb','hide (feelings','DISSIMULATE'),
 ('Noun','structure consisting of a row of evenly spaced columns, a structure composed of a series of arches supported by columns','COLONNADE'),
 ('Noun','a state of fitness and good health','FETTLE'),
 ('Verb','remove mold marks or sand from (a casting','FETTLE'),
 ('Noun','(behavioral attributes','DEPORTMENT'),
 ('Verb','describe roughly or briefly or give the main points or summary of, give to understand','ADUMBRATE'),
 ('Adjective','easily managed (controlled or taught or molded, responsive to suggestions and influences','TRACTABLE'),
 ('Adjective','capable of being protruded or stretched or opened out','EXTENSILE'),
 ('Noun','a prominent forelock (especially one brushed upward from the forehead','QUIFF'),
 ('Noun','equality of distribution','EQUIPOISE'),
 ('Noun','assistance in time of difficulty','MINISTRATION'),
 ('Noun','a wig for men that was fashionable in the 17th and 18th centuries','PERUKE'),
 ('Adjective','heat-generating','CALORIFIC'),
 ('Verb','make neat, smart, or trim','TITTIVATE'),
 ('Adjective','sudden and severe','FULMINANT'),
 ('Noun','a gaping grimace','RICTUS'),
 ('Noun','lining consisting of material with a high melting point; used to line the inside walls of a furnace','REFRACTORY'),
 ('Adjective','not responding to treatment, temporarily unresponsive or not fully responsive to a process or stimulus, stubbornly resistant to authority or control','REFRACTORY'),
 ('Noun','a destructive and contagious bacterial disease of horses that can be transmitted to humans','GLANDERS'),
 ('Noun','a small stream, a small channel (as one formed by soil erosion','RILL'),
 ('Noun','a reckless and unprincipled reprobate','SCAPEGRACE'),
 ('Noun','a diplomat who is fully authorized to represent his or her government','PLENIPOTENTIARY'),
 ('Noun','(Roman Catholic Church) a book containing the texts used in the Catholic Mass throughout the year','MISSAL'),
 ('Verb','be teeming, be abuzz, move in large numbers, produce buds, branches, or germinate, become abundant; increase rapidly, breed freely and abundantly','PULLULATE'),
 ('Adjective','inclined to or marked by drowsiness, or slumbrous','SOMNOLENT'),
 ('Noun','a cheap lodging house','DOSSHOUSE'),
 ('Noun','small rounded bread either plain or sweet','BUN'),
 ('Verb','advance evidence for','ADDUCE'),
 ('Adjective','expressive of or exciting sexual love or romance','AMATORY'),
 ('Noun','one having both male and female sexual characteristics and organs; at birth an unambiguous assignment of male or female cannot be made','EPICENE'),
 ('Adjective','having an ambiguous sexual identity, having unsuitable feminine qualities','EPICENE'),
 ('Noun','a state of comatose torpor (as found in sleeping sickness, a feeling of lack of interest or energy, weakness characterized by a lack of vitality or energy','LASSITUDE'),
 ('Noun','lack of self-confidence','DIFFIDENCE'),
 ('Noun','any plant of the genus Veronica','VERONICA'),
 ('Verb','annoy continually or chronically','CHIVY'),
 ('Noun','a family of languages spoken by people scattered throughout central India','MUNDA'),
 ('Noun','an orgiastic festival in ancient Rome in honor of Saturn, a wild gathering involving excessive drinking and promiscuity','SATURNALIA'),
 ('Adjective','negligent of neatness especially in dress and person; habitually dirty and unkempt','FROWSY'),
 ('Noun','solid excretory product evacuated from the bowels','ORDURE'),
 ('Noun','a feeling of stupefied astonishment, marginal consciousness, the action of stupefying; making dull or lethargic','STUPEFACTION'),
 ('Adjective','having the attention diverted especially because of anxiety','DISTRAIT'),
 ('Adjective','smelling of beer','BEERY'),
 ('Adjective','(especially of certain salts','DELIQUESCENT'),
 ('Noun','a disdainful grimace','MOUE'),
 ('Adverb','in an ill-natured and tetchy manner','TETCHILY'),
 ('Noun','noisy quarrel, a noisy fight','AFFRAY'),
 ('Adjective','detrimental to health','INSALUBRIOUS'),
 ('Noun','power to influence or coerce','PUISSANCE'),
 ('Noun','the mistress of a chateau or large country house, a chain formerly worn at the waist by women; for carrying a purse or bunch of keys etc.','CHATELAINE'),
 ('Noun','the lofty nest of a bird of prey (such as a hawk or eagle, any habitation at a high altitude','EYRIE'),
 ('Noun','a gauge boson that mediates the (extremely weak','GRAVITON'),
 ('Noun','coiled barbed wire used as an obstacle, free-reed instrument played like an accordion by pushing its ends together to force air through the reeds','CONCERTINA'),
 ('Verb','collapse like a concertina','CONCERTINA'),
 ('Noun','state of disgrace resulting from public abuse, "a false accusation of an offense or a malicious misrepresentation of someones words or actions','OBLOQUY'),
 ('Noun','East Indian tree that puts out aerial shoots that grow down into the soil forming additional trunks, a loose fitting jacket; originally worn in India','BANYAN'),
 ('Noun','human conception without fertilization by a man, process in which an unfertilized egg develops into a new individual; common among insects and some other arthropods','PARTHENOGENESIS'),
 ('Verb','occupy in an agreeable, entertaining or pleasant fashion, play boisterously','DISPORT'),
 ('Noun','small pruning shears with a spring that holds the handles open and a single blade that closes against a flat surface','SECATEURS'),
 ('Noun','erosion by friction, the wearing down of rock particles by friction due to water or wind or ice, effort expended in moving one object over another with pressure','DETRITION'),
 ('Noun','the state of being imminent and liable to happen soon','IMMINENCE'),
 ('Noun','state of disgrace resulting from public abuse, a state of extreme dishonor','OPPROBRIUM'),
 ('Noun','a painful inflammation of the big toe and foot caused by defects in uric acid metabolism resulting in deposits of the acid and its salts in the blood and joints','GOUT'),
 ('Verb','insert (days','INTERCALATE'),
 ('Noun','(Jewish folklore','DYBBUK'),
 ('Noun','formal and explicit approval','IMPRIMATUR'),
 ('Noun','one of a series of hooks used to hold cloth on a tenter','TENTERHOOK'),
 ('Adjective','extremely pleasant in a gentle way, pleasing to the ear','DULCET'),
 ('Verb','lock up or confine, in or as in a jail','IMMURE'),
 ('Noun','the organic process of growing older and showing the effects of increasing age, the property characteristic of old age','SENESCENCE'),
 ('Noun','extreme gluttony, an excessive desire for wealth (usually in large amounts','RAPACIOUSNESS'),
 ('Adjective','having a lean and bony physique','RAWBONED'),
 ('Noun','a comic verse of irregular measure','DOGGEREL'),
 ('Noun','someone who dissipates resources self-indulgently','WASTREL'),
 ('Adjective','exercising power or authority','REGNANT'),
 ('Noun','a major branch of the Afro-Asiatic language family','SEMITIC'),
 ('Adjective','of or relating to the group of Semitic languages, of or relating to or characteristic of Semites','SEMITIC'),
 ('Noun','a helpful partner','HELPMEET'),
 ('Noun','people engaged in a particular occupation','SODALITY'),
 ('Noun','an organism or species surviving as a remnant of an otherwise extinct flora or fauna in an environment much changed from that in which it originated, geological feature that is a remnant of a pre-existing formation after other parts have disappeared','RELICT'),
 ('Noun','someone who makes and sells hats','MILLINER'),
 ('Noun','a pressing or urgent situation, a sudden unforeseen crisis (usually involving danger','EXIGENCY'),
 ('Noun','very spiny and dense evergreen shrub with fragrant golden-yellow flowers; common throughout western Europe','GORSE'),
 ('Adjective','acutely insightful and wise','SAPIENT'),
 ('Adjective','tormented or harassed by nightmares or unreasonable fears','HAGRIDDEN'),
 ('Verb','free from slavery or servitude','MANUMIT'),
 ('Noun','a British commissioned army officer below the rank of captain','SUBALTERN'),
 ('Adjective','inferior in rank or status','SUBALTERN'),
 ('Adjective','(especially of plants','ETIOLATED'),
 ('Noun','keeping watch over examination candidates to prevent cheating','INVIGILATION'),
 ('Noun','a period in a mans life corresponding to menopause", "the time in a womans life in which the menstrual cycle ends','CLIMACTERIC'),
 ('Verb','recite in elocution, speak against in an impassioned manner','DECLAIM'),
 ('Noun','the chief steward or butler of a great household','SENESCHAL'),
 ('Adjective','(of birds, (of an arrow','FLEDGED'),
 ('Noun','a homeless girl who roams the streets, a girl of impish appeal','GAMINE'),
 ('Adjective','overtaken by night or darkness, or nighted, lacking enlightenment or knowledge or culture','BENIGHTED'),
 ('Noun','a framework of steel bars raised on side supports to bridge over or around something; can display railway signals above several tracks or can support a traveling crane etc.','GANTRY'),
 ('Noun','(Hinduism','MAHABHARATA'),
 ('Adjective','mentally or physically infirm with age','SENILE'),
 ('Verb','corrupt morally or by intemperance or sensuality, make imperfect, take away the legal force of or render ineffective','VITIATE'),
 ('Adjective','extremely filthy from long neglect','AUGEAN'),
 ('Noun','the position or authority of a suzerain, the domain of a suzerain','SUZERAINTY'),
 ('Noun','a sharp metal spike or spur that is fastened to the leg of a gamecock, a spar rising aft from a mast to support the head of a quadrilateral fore-and-aft sail, an iron hook with a handle; used for landing large fish','GAFF'),
 ('Verb','fondle or pet affectionately','CANOODLE'),
 ('Noun','a small cave (usually with attractive features','GROT'),
 ('Noun','informal terms for money','PELF'),
 ('Noun','the trait of behaving in an obscene manner','SALACITY'),
 ('Noun','an abnormal state in which the normal flow of a liquid (such as blood, inactivity resulting from a static balance between opposing forces','STASIS'),
 ('Noun','a period of five years, a ceremonial purification of the Roman population every five years following the census','LUSTRUM'),
 ('Noun','the patterns of stress and intonation in a language, (prosody, the study of poetic meter and the art of versification','PROSODY'),
 ('Noun','weakness characterized by a lack of vitality or energy, exhaustion resulting from lack of food','INANITION'),
 ('Adjective','capable of retraction; capable of being drawn back','RETRACTILE'),
 ('Noun','using more words than necessary','PLEONASM'),
 ('Noun','a wooden instrument of punishment on a post with holes for the wrists and neck; offenders were locked in and so exposed to public scorn','PILLORY'),
 ('Verb','expose to ridicule or public scorn, punish by putting in a pillory, criticize harshly or violently','PILLORY'),
 ('Noun','the straight line configuration of 3 celestial bodies (as the sun and earth and moon','SYZYGY'),
 ('Noun','small edible marine snail; steamed in wine or baked, edible marine gastropod','WINKLE'),
 ('Verb','emit or reflect light in a flickering manner, gleam or glow intermittently, remove or displace from a position','WINKLE'),
 ('Adjective','shaped like a cross','CRUCIFORM'),
 ('Noun','very spiny and dense evergreen shrub with fragrant golden-yellow flowers; common throughout western Europe, small Eurasian shrub having clusters of yellow flowers that yield a dye; common as a weed in Britain and the United States; sometimes grown as an ornamental, any of various hard colored rocks (especially rocks consisting of chert or basalt','WHIN'),
 ('Noun','a cudgel used to give someone a beating on the soles of the feet, a form of torture in which the soles of the feet are beaten with whips or cudgels','BASTINADO'),
 ('Verb','beat somebody on the soles of the feet','BASTINADO'),
 ('Noun','a variable color that is vivid red but sometimes with an orange tinge','VERMILION'),
 ('Verb','color vermilion','VERMILION'),
 ('Adjective','of a vivid red to reddish-orange color','VERMILION'),
 ('Adjective','of or pertaining to construction or architecture','ARCHITECTONIC'),
 ('Noun','the process of giving birth','PARTURITION'),
 ('Adjective','having the sticky properties of an adhesive','VISCID'),
 ('Adjective','of or relating to the Hebrides','HEBRIDEAN'),
 ('Adjective','softly bright or radiant','LUCENT'),
 ('Adjective','relating to or written for or in the style of a Greek chorus','CHORIC'),
 ('Noun','the reappearance in a painting of an underlying image that had been painted over (usually when the later painting becomes transparent with age','PENTIMENTO'),
 ('Noun','a strong cotton fabric with a raised pattern; used for bedcovers and curtains','DIMITY'),
 ('Noun','a territory in southwestern Germany formerly ruled by the counts palatine, a territory under the jurisdiction of a count palatine','PALATINATE'),
 ('Noun','the inflection of nouns and pronouns and adjectives in Indo-European languages, process of changing to an inferior state, a downward slope or bend, a class of nouns or pronouns or adjectives in Indo-European languages having the same (or very similar','DECLENSION'),
 ('Verb','melt away in the process of decay, melt or become liquid by absorbing moisture from the air','DELIQUESCE'),
 ('Noun','an inscription on a tombstone or monument in memory of the person buried there, a summary statement of commemoration for a dead person','EPITAPH'),
 ('Adjective','relating to or characteristic of or according to the rules of counterpoint, having two or more independent but harmonically related melodic parts sounding together','CONTRAPUNTAL'),
 ('Noun','the language or speech of one individual at a particular period in life','IDIOLECT'),
 ('Noun','woolly usually horned ruminant mammal related to the goat, a timid defenseless simpleton who is readily preyed upon, a docile and vulnerable person who would rather follow than make an independent decision','SHEEP'),
 ('Adverb','in an equable manner','EQUABLY'),
 ('Noun','a twilled woolen fabric','SERGE'),
 ('Adjective','not friendly','INIMICAL'),
 ('Noun','a corrupt or depraved or degenerate act or practice','TURPITUDE'),
 ('Noun','a continuant consonant produced by breath moving against a narrowing of the vocal tract','FRICATIVE'),
 ('Adjective','of speech sounds produced by forcing air through a constricted passage (as `f, `s, `z, or `th in both `thin and `then','FRICATIVE'),
 ('Noun','deductive reasoning in which a conclusion is derived from two premises','SYLLOGISM'),
 ('Noun','foam or froth on the sea','SPUME'),
 ('Verb','make froth or foam and become bubbly','SPUME'),
 ('Verb','formally reject or disavow a formerly held belief, usually under pressure','ABJURE'),
 ('Adjective','short and plump','PODGY'),
 ('Adjective','of or relating to the time before the Fall of Adam and Eve','PRELAPSARIAN'),
 ('Adjective','of or belonging to or active during the day, having a daily cycle or occurring every day','DIURNAL'),
 ('Noun','a strong creative impulse; divine inspiration','AFFLATUS'),
 ('Noun','a fringe region of partial shadow around an umbra','PENUMBRA'),
 ('Noun','food for domestic livestock, a stock or supply of foods','PROVENDER'),
 ('Noun','an architectural support or base (as for a column or statue','PLINTH'),
 ('Noun','a man who is effeminate in his manner and fussy in the way he dresses, someone who procures customers for whores (in England they call a pimp a ponce','PONCE'),
 ('Noun','a small stream','RUNNEL'),
 ('Verb','place in a grave or tomb','INHUME'),
 ('Noun','a whip with a lash of leather thongs twisted with wire; used for flogging prisoners','KNOUT'),
 ('Adjective','of noxious stench from atmospheric pollution','MEPHITIC'),
 ('Noun','earliest horse; extinct primitive dog-sized four-toed Eocene animal','EOHIPPUS'),
 ('Adjective','exacting especially about details','FINICAL'),
 ('Adjective','resembling or characteristic of or appropriate to an elegy, expressing sorrow often for something past','ELEGIAC'),
 ('Verb','retire and pension (someone, declare to be obsolete, become obsolete, retire or become ineligible because of old age or infirmity','SUPERANNUATE'),
 ('Verb','wander aimlessly, talk indistinctly; usually in a low voice, speak (about unimportant matters','MAUNDER'),
 ('Verb','be appropriate or necessary','BEHOVE'),
 ('Noun','an awkward bad-mannered adolescent boy','HOBBLEDEHOY'),
 ('Noun','great and constant diligence and attention','ASSIDUITY'),
 ('Noun','inflammation of the nose and throat with increased production of mucus','CATARRH'),
 ('Adjective','relating to the antipodes or situated at opposite sides of the earth','ANTIPODEAN'),
 ('Noun','a barn for cows','COWSHED'),
 ('Noun','a flamboyant deceiver; one who attracts customers with tricks or jokes','MOUNTEBANK'),
 ('Noun','a state of extreme poverty or destitution','PENURY'),
 ('Adjective','not having enough money to pay for necessities, excessively unwilling to spend','PENURIOUS'),
 ('Noun','a long steep slope or cliff at the edge of a plateau or ridge; usually formed by erosion, a steep artificial slope in front of a fortification','ESCARPMENT'),
 ('Noun','a Celtic language of Wales','CYMRIC'),
 ('Adjective','marked by spirited enjoyment, informal or slang terms for mentally irregular','BARMY'),
 ('Noun','the first largest innermost toe','HALLUX'),
 ('Adjective','demanding attention, requiring precise accuracy','EXIGENT'),
 ('Noun','round gourd of the calabash tree, tropical American evergreen that produces large round gourds, Old World climbing plant with hard-shelled bottle-shaped gourds as fruits, bottle made from the dried shell of a bottle gourd, a pipe for smoking; has a curved stem and a large bowl made from a calabash gourd','CALABASH'),
 ('Adjective','involving or having two dimensions','PLANAR'),
 ('Noun','small Australian parakeet usually light green with black and yellow markings in the wild but bred in many colors','BUDGERIGAR'),
 ('Noun','decoration that is hung (as a tapestry, a form of capital punishment; victim is suspended by the neck from a gallows or gibbet until dead, the act of suspending something (hanging it from above so it moves freely','HANGING'),
 ('Noun','a pause or interruption (as in a conversation, a break or pause (usually for sense','CAESURA'),
 ('Noun','an acquired skin disease characterized by patches of unpigmented skin (often surrounded by a heavily pigmented border','VITILIGO'),
 ('Adjective','dwelling beneath the surface of the earth','CHTHONIC'),
 ('Verb','transfer power to someone, appoint as a substitute, give an assignment to (a person, a person','DEPUTE'),
 ('Adjective','having power to atone for or offered by way of expiation or propitiation, or propitiatory, intended to reconcile or appease','PROPITIATORY'),
 ('Noun','a benefice to which no spiritual or pastoral duties are attached, an office that involves minimal duties','SINECURE'),
 ('Noun','a false accusation of an offense or a malicious misrepresentation of someones words or actions", "an abusive attack on a persons character or good name','CALUMNY'),
 ('Noun','the territorial jurisdiction of a bishop','BISHOPRIC'),
 ('Verb','turn pale, as if in fear','BLENCH'),
 ('Adjective','elaborately or excessively ornamented, having the deep slightly brownish color of gold, or golden','AUREATE'),
 ('Noun','applies to nonhuman mammals: a state or period of heightened sexual arousal and activity, type genus of the Oestridae: sheep botflies','OESTRUS'),
 ('Noun','(archaic, the monthly discharge of blood from the uterus of nonpregnant women from puberty to menopause','MENSTRUUM'),
 ('Noun','a bottomless gulf or pit; any unfathomable (or apparently unfathomable, often used figuratively','ABYSM'),
 ('Noun','a message that departs from the main subject, a turning aside (of your course or attention or concern','DIVAGATION'),
 ('Noun','medium-sized larch of Canada and northern United States including Alaska having a broad conic crown and rust-brown scaly bark','TAMARACK'),
 ('Adjective','defiantly aggressive','TRUCULENT'),
 ('Noun','a small spiked wheel at the end of a spur','ROWEL'),
 ('Adjective','serving no useful purpose; having no excuse for being, producing no result or effect, disinclined to work or exertion','OTIOSE'),
 ('Adjective','(used especially of vegetation','SERE'),
 ('Noun','an oil reservoir in an internal combustion engine, a well or other hole in which water has collected, a covered cistern; waste water and sewage flow into it','SUMP'),
 ('Noun','a stream or brook','ARROYO'),
 ('Noun','a round shape formed by a series of concentric circles (as formed by leaves or flower petals','GYRE'),
 ('Noun','a common cyst of the skin; filled with fatty matter (sebum','WEN'),
 ('Noun','spray blown up from the surface of the sea','SPINDRIFT'),
 ('Noun','a small pond of standing water','MERE'),
 ('Noun','(Hinduism and Buddhism','SAMSARA'),
 ('Noun','basic principles of the cosmos; also: an ancient sage in Hindu mythology worshipped as a god by some lower castes','DHARMA'),
 ('Adjective','tending to find and call attention to faults','CAPTIOUS'),
 ('Adjective','characterized by or of the nature of or using mimesis, exhibiting mimicry','MIMETIC'),
 ('Noun','a decorated bier on which a coffin rests in state during a funeral','CATAFALQUE'),
 ('Adjective','unwillingness to do something contrary to your custom, "(usually followed by `to','LOTH'),
 ('Noun','a girl who behaves in a boyish manner','HOYDEN'),
 ('Noun','someone to whom a legacy is bequeathed','LEGATEE'),
 ('Adjective','unpleasantly and excessively suave or ingratiating in manner or speech','FULSOME'),
 ('Adjective','moving easily and quickly; nimble, carefree and happy and lighthearted','LIGHTSOME'),
 ('Noun','one who observes Saturday as the Sabbath (as in Judaism','SABBATARIAN'),
 ('Adjective','pertaining to the Sabbath and its observance','SABBATARIAN'),
 ('Adjective','covered with or consisting of bushes or thickets','BOSKY'),
 ('Noun','a bell tower; usually stands alone unattached to a building','CAMPANILE'),
 ('Noun','the state of being weak in health or body (especially from old age','DEBILITY'),
 ('Noun','a size of paper used especially in Britain','FOOLSCAP'),
 ('Noun','(Roman Catholic Church, a type of lift having a chain of open compartments that move continually in an endless loop so that (agile','PATERNOSTER'),
 ('Noun','a collection of writings published in honor of a scholar','FESTSCHRIFT'),
 ('Noun','a person seized by nympholepsy','NYMPHOLEPT'),
 ('Noun','a sharp curve or crook; a shape resembling a hook, a musical note having the time value of a quarter of a whole note, a strange attitude or habit, a small tool or hooklike implement','CROTCHET'),
 ('Noun','part of an interior wall rising above the adjacent roof with windows admitting light','CLERESTORY'),
 ('Noun','uncastrated adult male sheep','TUP'),
 ('Noun','righteousness as a consequence of being honorable and honest','RECTITUDE'),
 ('Noun','a laborer who loads and unloads vessels in a port','DOCKER'),
 ('Adjective','expressing, composed of, or based on an analogy','ANALOGICAL'),
 ('Noun','living quarters reserved for wives and concubines and female relatives in a Muslim household','SERAGLIO'),
 ('Noun','the act of detecting something; catching sight of something','ESPIAL'),
 ('Verb','make believe with the intent to deceive, hide under a false appearance, behave unnaturally or affectedly','DISSEMBLE'),
 ('Noun','extensive landed property (especially in the country, territory over which rule or control is exercised','DEMESNE'),
 ('Noun','inability to control the flow of urine and involuntary urination','ENURESIS'),
 ('Adjective','characterized by propriety and dignity and good taste in manners and conduct, according with custom or propriety','DECOROUS'),
 ('Noun','harsh criticism or disapproval','ANIMADVERSION'),
 ('Adjective','having or showing arrogant superiority to and disdain of those one views as unworthy, expressive of contempt','SUPERCILIOUS'),
 ('Noun','the cardinal number that is the sum of three and one','QUATERNION'),
 ('Verb','to move or force, especially in an effort to get something open, make an uninvited or presumptuous inquiry, regard highly; think much of','PRISE'),
 ('Noun','an Irish girl','COLLEEN'),
 ('Noun','an artificial or inferior substitute or imitation','ERSATZ'),
 ('Adjective','artificial and inferior','ERSATZ'),
 ('Noun','a female fool','FLIBBERTIGIBBET'),
 ('Noun','someone skilled in the transcription of speech (especially dictation','AMANUENSIS'),
 ('Noun','a cosmetic preparation used by women in Egypt and Arabia to darken the edges of their eyelids','KOHL'),
 ('Noun','old breed of tall swift keen-eyed hunting dogs resembling greyhounds; from Egypt and southwestern Asia','SALUKI'),
 ('Adjective','of or associated with or requiring the use of the mind','NOETIC'),
 ('Verb','get up on the back of','BESTRIDE'),
 ('Noun','an instance of sudden interruption','ABRUPTION'),
 ('Noun','an aggregation or continuous network of urban communities','CONURBATION'),
 ('Noun','an ancient jar with two handles and a narrow neck; used to hold oil or wine','AMPHORA'),
 ('Noun','a tuberous Mexican herb having grasslike leaves and cultivated for its spikes of highly fragrant lily-like waxy white flowers','TUBEROSE'),
 ('Noun','a spoken blessing','BENISON'),
 ('Adjective','harshly critical or expressing censure','CENSORIOUS'),
 ('Verb','charge falsely or with malicious intent; attack the good name and reputation of someone','ASPERSE'),
 ('Noun','a light piece of music for piano, something of little value or significance, a table game in which short cues are used to knock balls into holes that are guarded by wooden pegs; penalties are incurred if the pegs are knocked over','BAGATELLE'),
 ('Noun','something that provides guidance (as Polaris guides mariners, something that strongly attracts attention and admiration','CYNOSURE'),
 ('Adjective','suffering from excessive eating or drinking, given to gross intemperance in eating or drinking','CRAPULOUS'),
 ('Verb','color purple','EMPURPLE'),
 ('Noun','a member of any of various Indian peoples of central Mexico, the Uto-Aztecan language spoken by the Nahuatl','NAHUATL'),
 ('Noun','feeding that consists of the delivery of a nutrient solution (as through a nasal tube','GAVAGE'),
 ('Adjective','of visual imagery of almost photographic accuracy','EIDETIC'),
 ('Adjective','evincing the presence of a deity, of or relating to or characteristic of a numen','NUMINOUS'),
 ('Adjective','acutely insightful and wise, mentally acute or penetratingly discerning','PERSPICACIOUS'),
 ('Adjective','belonging to some prior time','ERSTWHILE'),
 ('Adverb','at a previous time','ERSTWHILE'),
 ('Adjective','larger than normal for its kind','OVERSIZED'),
 ('Noun','a grotesque black doll','GOLLIWOG'),
 ('Verb','disappear gradually','EVANESCE'),
 ('Noun','(ethnic slur','PICKANINNY'),
 ('Noun','cocked hat with the brim turned up to form three points','TRICORNE'),
 ('Noun','intelligence manifested by being astute (as in business dealings, the capacity to assess situations or circumstances shrewdly and to draw sound conclusions','PERSPICACITY'),
 ('Adjective','tending to diminish sexual desire','ANAPHRODISIAC'),
 ('Noun','a monument built to honor people whose remains are interred elsewhere or whose remains cannot be recovered','CENOTAPH'),
 ('Noun','someone who collaborates with an enemy occupying force','QUISLING'),
 ('Noun','a variety of mandarin orange, medium-sized largely seedless mandarin orange with thin smooth skin','SATSUMA'),
 ('Noun','any of the bones of the fingers or toes, any closely ranked crowd of people, a body of troops in close array','PHALANX'),
 ('Noun','extreme excess','PLETHORA'),
 ('Noun','the iridescent internal layer of a mollusk shell','NACRE'),
 ('Noun','a person who has taught himself','AUTODIDACT'),
 ('Noun','a mound of stones piled up as a memorial or to mark a boundary or path, small rough-haired breed of terrier from Scotland','CAIRN'),
 ('Noun','a tumor arising in the meninges which surround the brain and spinal cord; usually slow growing and sometimes malignant','MENINGIOMA'),
 ('Adjective','relating to or containing gnomes','GNOMIC'),
 ('Noun','rapid and indistinct speech','GABBLE'),
 ('Verb','speak (about unimportant matters','GABBLE'),
 ('Noun','ice crystals forming a white deposit (especially on objects outside, correspondence in the sounds of two or more lines (especially final sounds','RIME'),
 ('Verb','be similar in sound, especially with respect to the last syllable, compose rhymes','RIME'),
 ('Noun','leaves of the tobacco plant dried and prepared for smoking or ingestion','BACCY'),
 ('Noun','a cigar with both ends cut flat','CHEROOT'),
 ('Noun','a small natural hill','HILLOCK'),
 ('Adverb','in accord with physical laws','PHYSICALLY'),
 ('Verb','make a noise typical of an engine lacking lubricants, bombard with heavy shells, explode heavily or with a loud dull noise','CRUMP'),
 ('Noun','a person who is not very bright','PILLOCK'),
 ('Noun','a kind of pick that is used for digging; has a flat blade set at right angles to the handle','MATTOCK'),
 ('Noun','a shard of pottery','POTSHERD'),
 ('Noun','a person who professes beliefs and opinions that he or she does not hold in order to conceal his or her real feelings or motives','HYPOCRITE'),
 ('Noun','an annual Eurasian plant cultivated in North America having showy heads of blue or purple or pink or white flowers, blowfly with iridescent blue body; makes a loud buzzing noise in flight','BLUEBOTTLE'),
 ('Noun','a vitrified substance; the glassy result of being vitrified, the process of becoming vitreous','VITRIFICATION'),
 ('Noun','a strong post (as on a wharf or quay or ship for attaching mooring lines','BOLLARD'),
 ('Noun','the crescent-shaped area at the base of the human fingernail, a crescent-shaped metal ornament of the Bronze Age','LUNULA'),
 ('Noun','an ancient Egyptian mud-brick tomb with a rectangular base and sloping sides and flat roof','MASTABA'),
 ('Noun','after death the soul begins a new cycle of existence in another human body','METEMPSYCHOSIS'),
 ('Adjective','transmitting light; able to be seen through with clarity, (of language','PELLUCID'),
 ('Noun','a feather covering the shoulder of a bird, garment consisting of a long wide piece of woolen cloth worn over the shoulders with an opening for the head; part of a monastic habit','SCAPULAR'),
 ('Adjective','relating to or near the shoulder blade','SCAPULAR'),
 ('Noun','a cloth used as a head covering (and veil and shawl','CHADOR'),
 ('Noun','the branch of theology that is concerned with such final things as death and Last Judgment; Heaven and Hell; the ultimate destiny of humankind','ESCHATOLOGY'),
 ('Noun','localized necrosis resulting from obstruction of the blood supply','INFARCT'),
 ('Noun','a farm dumpcart for carrying dung; carts of this type were used to carry prisoners to the guillotine during the French Revolution','TUMBREL'),
 ('Noun','short-tailed wildcats with usually tufted ears; valued for their fur, large American feline resembling a lion','CATAMOUNT'),
 ('Adverb','at right angles to the length of a ship or airplane','ABEAM'),
 ('Noun','the application of very thin coat of color over the surface of a picture','SCUMBLE'),
 ('Noun','a long slender cigar','PANATELA'),
 ('Noun','someone who flees from an uncongenial situation, contempt expressed by mockery in looks or words','FLEER'),
 ('Verb','to smirk contemptuously','FLEER'),
 ('Noun','large heavy rope for nautical use','HAWSER'),
 ('Adjective','difficult to handle or use especially because of size or weight','CUMBROUS'),
 ('Verb','affect with wonder, be a mystery or bewildering to','AMAZE'),
 ('Noun','a large gathering of people of a particular type, a flock of birds (especially when gathered close together on the ground','BEVY'),
 ('Adjective','resembling a labyrinth in form or complexity','MAZY'),
 ('Noun','a member of the Nepalese force that has been part of the British army for 200 years; known for fierceness in combat, a member of Hindu people descended from brahmins and Rajputs who live in Nepal','GURKHA'),
 ('Noun','a piece of ornamented cloth that protects the back of a chair from hair oils','ANTIMACASSAR'),
 ('Noun','a fragment broken off from the edge or face of stone or ore and having at least one thin edge','SPALL'),
 ('Noun','abusive or venomous language used to express blame or censure or bitter deep-seated ill will','VITUPERATION'),
 ('Noun','a band of material around the waist that strengthens a skirt or trousers','CINCTURE'),
 ('Noun','a piece of starched cloth covering the shoulders of a nuns habit", a short blouse with sleeves that is worn under a jumper or pinafore dress','GUIMPE'),
 ('Noun','a woman who cohabits with an important man','DOXY'),
 ('Noun','any of several deciduous Asian trees of the genus Ailanthus','AILANTHUS'),
 ('Noun','any of various reptiles of the suborder Sauria which includes lizards; in former classifications included also the crocodiles and dinosaurs','SAURIAN'),
 ('Adjective','of or relating to lizards','SAURIAN'),
 ('Noun','a rope for raising or lowering a sail or flag','HALYARD'),
 ('Verb','treat with excessive indulgence','COSSET'),
 ('Adjective','characterized by great caution and wariness','CHARY'),
 ('Noun','a flowery and highly rhetorical oration, (rhetoric','PERORATION'),
 ('Noun','something hard to endure, harshness of manner','ASPERITY'),
 ('Noun','omission of a sound between two words (usually a vowel and the end of one word or the beginning of the next, a deliberate act of omission','ELISION'),
 ('Noun','the doctrine that irredenta should be controlled by the country to which they are ethnically or historically related','IRREDENTISM'),
 ('Noun','a railway up the side of a mountain pulled by a moving cable and having counterbalancing ascending and descending cars','FUNICULAR'),
 ('Adjective','relating to or operated by a cable','FUNICULAR'),
 ('Noun','a fold of tissue that partly covers the entrance to the vagina of a virgin','MAIDENHEAD'),
 ('Noun','a large low horse-drawn wagon without sides, a large truck designed to carry heavy loads; usually without sides','LORRY'),
 ('Noun','an illusory feat; considered magical by naive observers','LEGERDEMAIN'),
 ('Noun','a porch or entrance to a building consisting of a covered and often columned area','PORTICO'),
 ('Noun','delight in another persons misfortune','SCHADENFREUDE'),
 ('Noun','foolish fondness for or excessive submissiveness to ones wife','UXORIOUSNESS'),
 ('Adjective','of or characteristic of or resembling a lion','LEONINE'),
 ('Noun','a sudden and violent collapse','FIASCO'),
 ('Noun','a hanging fold of loose skin on an elderly persons neck','DEWLAP'),
 ('Noun','a favorite saying of a sect or political group, a manner of speaking that is distinctive of a particular group of people','SHIBBOLETH'),
 ('Noun','a white insoluble fibrous protein formed by the action of thrombin on fibrinogen when blood clots; it forms a network that traps red cells and platelets','FIBRIN'),
 ('Noun','a group of African languages in the Niger-Congo group spoken from Senegal east as far as the Ivory Coast','MANDE'),
 ('Noun','a military engineer who does sapping (digging trenches or undermining fortifications','SAPPER'),
 ('Noun','someone who is drafted into military service','CONSCRIPT'),
 ('Verb','enroll into service compulsorily','CONSCRIPT'),
 ('Noun','French philosopher and writer born in Switzerland; believed that the natural goodness of man was warped by society; ideas influenced the French Revolution (1712-1778, French primitive painter (1844-1910','ROUSSEAU'),
 ('Noun','a contrary command cancelling or reversing a previous command','COUNTERMAND'),
 ('Verb','cancel officially','COUNTERMAND'),
 ('Noun','a state of inactivity or disuse','DESUETUDE'),
 ('Noun','(mathematics, as a straight line on a plane or an arc of a great circle on a sphere','GEODESIC'),
 ('Adjective','of or relating to or determined by geodesy','GEODESIC'),
 ('Noun','a cry of praise or adoration (to God','HOSANNA'),
 ('Noun','the personal outfit of a bride; clothes and accessories and linens','TROUSSEAU'),
 ('Noun','a member of a nomadic Berber people of the Sahara, the dialect of Berber spoken by the Tuareg','TUAREG'),
 ('Noun','a long stretch of open level ground (paved or grassy','ESPLANADE'),
 ('Noun','a massive inexorable force that seems to crush everything in its way, an avatar of Vishnu, a crude idol of Krishna','JUGGERNAUT'),
 ('Noun','arborescent cacti having very spiny cylindrical stem segments; southwestern United States and Mexico','CHOLLA'),
 ('Noun','the quality of being outrageous, vastness of size or extent, the quality of extreme wickedness, an act of extreme wickedness','ENORMITY'),
 ('Noun','a small usually single-celled asexual reproductive body produced by many nonflowering plants and fungi and some bacteria and protozoans and that are capable of developing into a new individual without sexual fusion','SPORE'),
 ('Noun','the region of the shore of a lake or sea or ocean','LITTORAL'),
 ('Adjective','of or relating to a coastal or shore region','LITTORAL'),
 ('Noun','the girlfriend of a gangster','MOLL'),
 ('Noun','a mere wish, unaccompanied by effort to obtain, volition in its weakest form','VELLEITY'),
 ('Verb','march out (as from a defile, pass out or emerge; especially of rivers','DEBOUCH'),
 ('Noun','the part of a modern theater stage between the curtain and the orchestra (i.e., in front of the curtain, the wall that separates the stage from the auditorium in a modern theater','PROSCENIUM'),
 ('Noun','the present occasion','NONCE'),
 ('Adjective','characterized by soft sounds','MURMUROUS'),
 ('Noun','English form of rondeau having three triplets with a refrain after the first and third, round piece of armor plate that protects the armpit, (heraldry','ROUNDEL'),
 ('Noun','the fur of young lambs, a city in southwestern Russia on the delta of the Volga River','ASTRAKHAN'),
 ('Verb','utter speech sounds','PHONATE'),
 ('Noun','an automatic signal (usually a sound','ALARUM'),
 ('Noun','a simplified cursive form of the ancient hieratic script, the modern Greek vernacular','DEMOTIC'),
 ('Adjective','of or written in or belonging to the form of modern Greek based on colloquial use, of or for the common people','DEMOTIC'),
 ('Noun','a province of northeastern South Africa originally inhabited by Africans who spoke Bantu; colonized by the Boers','TRANSVAAL'),
 ('Verb','deduce (a principle, a meaning, develop or evolve from a latent or potential state','EDUCE'),
 ('Adjective','having a frosted look from a powdery coating, as on plants','GLAUCOUS'),
 ('Adjective','having a flat circular shape','DISCOID'),
 ('Noun','Eurasian herb having small yellow flowers and red roots formerly an important source of the dye alizarin','MADDER'),
 ('Verb','color a moderate to strong red','MADDER'),
 ('Verb','move unobtrusively or furtively, move sideways','SIDLE'),
 ('Noun','music composed for dancing the pavane, a stately court dance of the 16th and 17th centuries','PAVANE'),
 ('Adjective','very long lasting','PERDURABLE'),
 ('Noun','an archaic term for a boundary, an archaic term for a goal or destination','BOURN'),
 ('Noun','a bright green fabric napped to resemble felt; used to cover gaming tables','BAIZE'),
 ('Noun','the sound of a bell rung in Roman Catholic churches to announce the time when the Angelus should be recited, a prayer said 3 times a day by Roman Catholics in memory of the Annunciation','ANGELUS'),
 ('Noun','a Russian prison camp for political prisoners','GULAG'),
 ('Noun','herbs or shrubs or small trees: flowering maple; Indian mallow','ABUTILON'),
 ('Adjective','slightly insane, suggestive of an elf in strangeness and otherworldliness','FEY'),
 ('Noun','(Greek mythology, the largest moon of Neptune, tropical marine gastropods having beautifully colored spiral shells, small usually bright-colored semiaquatic salamanders of North America and Europe and northern Asia','TRITON'),
 ('Noun','a transparent thermoplastic acrylic resin','PERSPEX'),
 ('Noun','a bridge hand that is void of trumps, a movable barrier used in motor racing; sometimes placed before a dangerous corner to reduce speed as cars pass in single file, the use of tricks to deceive someone (usually to extract money from them','CHICANE'),
 ('Verb','defeat someone through trickery or deceit, raise trivial objections','CHICANE'),
 ('Noun','a musical phrase repeated over and over during a composition','OSTINATO'),
 ('Noun','one or more large merchant ships','ARGOSY'),
 ('Noun','a hat made of felt with a creased crown','HOMBURG'),
 ('Noun','(Yiddish','NUDNIK'),
 ('Noun','a card game for two players using a reduced pack of 32 cards, a form of military punishment used by the British in the late 17th century in which a soldier was forced to stand on one foot on a pointed stake','PIQUET'),
 ('Noun','the herd of horses from which those to be used the next day are chosen','REMUDA'),
 ('Noun','a musical instrument consisting of graduated steel plates that are struck by hammers activated by a keyboard','CELESTA'),
 ('Adverb','to a remarkable degree or extent','UNUSUALLY'),
 ('Adjective','growing or remaining under water','SUBAQUEOUS'),
 ('Noun','a person who returns after a lengthy absence, someone who has returned from the dead','REVENANT'),
 ('Adjective','of or relating to or typical of a revenant, coming back','REVENANT'),
 ('Noun','the brother of your father or mother; the husband of your aunt, a source of help and advice and encouragement','UNCLE'),
 ('Noun','a lyric soprano who specializes in coloratura vocal music, singing with florid ornamentation','COLORATURA'),
 ('Noun','a flat protective covering (on a door or wall etc, (nautical, a shield; especially one displaying a coat of arms','ESCUTCHEON'),
 ('Noun','the act of throwing someone or something out of a window','DEFENESTRATION'),
 ('Noun','a fine point of etiquette or petty formality, strict observance of formalities','PUNCTILIO'),
 ('Adjective','inclined to a healthy reddish color often associated with outdoor life','RUBICUND'),
 ('Noun','music composed in six-eight time for dancing the tarantella, a lively whirling Italian dance for two persons','TARANTELLA'),
 ('Adjective','of or relating to or giving birth, giving birth','PARTURIENT'),
 ('Adjective','of or relating to or dealing with or regarding the ultimate destiny of mankind and the world','ESCHATOLOGICAL'),
 ('Adverb','as follows','VIDELICET'),
 ('Adjective','of or concerned with or related to the future','PROSPECTIVE'),
 ('Adjective','occurring without loss or gain of heat','ADIABATIC'),
 ('Noun','a communication that belittles somebody or something','DEROGATION'),
 ('Noun','a formal speech giving advice or a warning.','ALLOCUTION'),
 ('Noun','a desire for sexual intimacy','CONCUPISCENCE'),
 ('Noun','an utterance made by exhaling audibly','SUSPIRATION'),
 ('Adjective','having or revealing little emotion or sensibility; not easily aroused or excited','STOLID'),
 ('Noun','a native or inhabitant of Denmark','DANE'),
 ('Noun','a cord fastened around the neck with an ornamental clasp and worn as a necktie, long heavy knife with a single edge; of Philippine origin','BOLO'),
 ('Adjective','convex on both sides; shaped like a lentil','LENTICULAR'),
 ('Adverb','in essence; at bottom or by ones (or its','BASICALLY'),
 ('Noun','a quotation at the beginning of some piece of writing, an engraved inscription','EPIGRAPH'),
 ('Adjective','of very poor quality or condition, unequivocally detestable, deserving a curse','EXECRABLE'),
 ('Verb','make a murmuring sound','SOUGH'),
 ('Adjective','having or causing a whirling sensation; liable to falling','VERTIGINOUS'),
 ('Verb','utter a sound, as with obvious effort, throw with great effort, rise and move, as in waves or billows, lift or elevate, move or cause to move in a specified way, direction, or position, breathe noisily, as when one is exhausted, bend out of shape, as under pressure or from heat, make an unsuccessful effort to vomit; strain to vomit','HOVE'),
 ('Noun','a strong north wind that blows in France during the winter','MISTRAL'),
 ('Noun','a vault or building where corpses or bones are deposited','CHARNEL'),
 ('Adjective','gruesomely indicative of death or the dead','CHARNEL'),
 ('Adjective','dark and gloomy','TENEBROUS'),
 ('Verb','cause to be confused emotionally','BEMUSE'),
 ('Noun','an alloy of tin with some copper and antimony; a lining for bearings that reduces friction','BABBITT'),
 ('Verb','line with a Babbitt metal','BABBITT'),
 ('Verb','make dim or indistinct','BLEAR'),
 ('Adjective','tired to the point of exhaustion','BLEAR'),
 ('Noun','an evasion of the point of an argument by raising irrelevant distinctions or objections, the essence that makes something the kind of thing it is and makes it different from any other','QUIDDITY'),
 ('Noun','a fibrous amphibole; used for making fireproof articles; inhaling fibers can cause asbestosis or lung cancer','ASBESTOS'),
 ('Adjective','of the nature of a homily or sermon, of or relating to homiletics','HOMILETIC'),
 ('Noun','an unnaturally frenzied or distraught woman, (Greek mythology','MAENAD'),
 ('Noun','the main river of Myanmar rising in the north and flowing south through the length of Burma to empty into the Andaman Sea','IRRAWADDY'),
 ('Noun','a tavern below street level featuring beer; originally a German restaurant in the basement of city hall','RATHSKELLER'),
 ('Noun','a fit of shivering or shaking, successive stages of chills and fever that is a symptom of malaria, a mark placed above a vowel to indicate pronunciation','AGUE'),
 ('Verb','unconsciously replace fact with fantasy in ones memory", talk socially without exchanging too much information, have a conference in order to talk something over','CONFABULATE'),
 ('Noun','a loose cloak with a hood; worn in the Middle East and northern Africa','JELLABA'),
 ('Noun','a fractional monetary unit in Egypt and Lebanon and Sudan and Syria, 100 kurus equal 1 lira in Turkey','PIASTER'),
 ('Noun','a member of any of various organizations that subsequently derived from the 17th-century society, a member of a secret 17th-century society of philosophers and scholars versed in mystical and metaphysical and alchemical lore','ROSICRUCIAN'),
 ('Adjective','of or relating to the Rosicrucians','ROSICRUCIAN'),
 ('Noun','a military recruit who is assigned menial tasks, a person serving a sentence in a jail or prison','YARDBIRD'),
 ('Noun','a colorless or yellowish oily liquid obtained by distillation of wood tar; used as an antiseptic, a dark oily liquid obtained by distillation of coal tar; used as a preservative for wood','CREOSOTE'),
 ('Verb','treat with creosote','CREOSOTE'),
 ('Noun','dense vegetation consisting of stunted trees or bushes','CHAPARRAL'),
 ('Noun','a Mexican-American teenager who belongs to a neighborhood gang and who dresses in showy clothes','PACHUCO'),
 ('Noun','someone who engages in drinking bouts, a drunken reveller; a devotee of Bacchus, (classical mythology','BACCHANT'),
 ('Noun','black-and-red or black-and-yellow orioles of the American tropics','CACIQUE'),
 ('Noun','a Mexican laborer who worked in the United States on farms and railroads in order to ease labor shortages during World War II','BRACERO'),
 ('Noun','a Chinese god worshipped in the form of an idol','JOSS'),
 ('Noun','a long cassock with buttons down the front; worn by Roman Catholic priests','SOUTANE'),
 ('Noun','something to which a mountain climbers rope can be secured','BELAY'),
 ('Verb','turn a rope round an object or person in order to secure it or him, fasten a boat to a bitt, pin, or cleat','BELAY'),
 ('Noun','a contestant who reaches the final stages of a competition','FINALIST'),
 ('Noun','shop selling womens hats", hats for women; the wares sold by a milliner','MILLINERY'),
 ('Noun','a container where religious relics are stored or displayed (especially relics of saints','RELIQUARY'),
 ('Verb','make amends for','EXPIATE'),
 ('Noun','a highly maneuverable escort warship; smaller than a destroyer','CORVETTE'),
 ('Noun','a loop knot that neither slips nor jams','BOWLINE'),
 ('Noun','a group of followers hired to applaud at a performance','CLAQUE'),
 ('Noun','a junction where two things (as paper or film or magnetic tape, joint made by overlapping two ends and joining them together','SPLICE'),
 ('Verb','join the ends of, perform a marriage ceremony, join together so as to form new genetic combinations, join by interweaving strands','SPLICE'),
 ('Noun','area around the altar of a church for the clergy and choir; often enclosed by a lattice or railing','CHANCEL'),
 ('Adjective','impossible to avoid or evade','INELUCTABLE'),
 ('Noun','insulting terms of address for people who are stupid or irritating or ridiculous, vulgar slang for anus','ASSHOLE'),
 ('Adjective','(quantifier, completely given to or absorbed by','ALL'),
 ('Adverb','to a complete degree or to the full or entire extent (`whole is often used informally for `wholly','ALL'),
 ('Noun','an early Christian ascetic who lived on top of high pillars','STYLITE'),
 ('Noun','the ability to sense the position and location and orientation and movement of the body and its parts','PROPRIOCEPTION'),
 ('Noun','the state or fact of existing, everything that exists anywhere','EXISTENCE'),
 ('Noun','the use of speech for informal exchange of views or ideas or information etc.','CONVERSATION'),
 ('Noun','a specialist in philosophy, a wise person who is calm and rational; someone who lives a life of reason with equanimity','PHILOSOPHER'),
 ('Noun','a womans drawstring handbag; usually made of net or beading or brocade; used in 18th and 19th centuries", a network of fine lines, dots, cross hairs, or wires in the focal plane of the eyepiece of an optical instrument','RETICULE'),
 ('Noun','an anthology of articles on a related subject or an anthology of the works of a single author, a vehicle carrying many passengers; used for public transport','OMNIBUS'),
 ('Adjective','providing for many things at once','OMNIBUS'),
 ('Adjective','having a projecting lower jaw','PROGNATHIC'),
 ('Adjective','negligent of neatness especially in dress and person; habitually dirty and unkempt','FROWZY'),
 ('Noun','the area on a billiard table behind the balkline, something immaterial that interferes with or delays action or progress, one of several parallel sloping beams that support a roof','BAULK'),
 ('Verb','refuse to comply','BAULK'),
 ('Noun','analysis of verse into metrical patterns','SCANSION'),
 ('Noun','a fold of peritoneum supporting the viscera','OMENTUM'),
 ('Noun','a song or hymn of mourning composed or performed as a memorial to a dead person','THRENODY'),
 ('Noun','the general region between the anus and the genital organs','PERINEUM'),
 ('Noun','the form of government of a social organization, a politically organized unit, shrewd or crafty management of public affairs','POLITY'),
 ('Noun','complete and confirmed integrity; having strong moral principles','PROBITY'),
 ('Adjective','being a bard or relating to a bards poetry','BARDIC'),
 ('Noun','any of various plants of the family Gentianaceae especially the genera Gentiana and Gentianella and Gentianopsis','GENTIAN'),
 ('Noun','part of the peritoneum attached to the stomach and to the colon and covering the intestines, the inner membrane of embryos in higher vertebrates (especially when covering the head at birth','CAUL'),
 ('Adjective','containing pus','PURULENT'),
 ('Adjective','in an advanced stage of pregnancy','GRAVID'),
 ('Noun','the act of despoiling a country in warfare','RAPINE'),
 ('Noun','a sudden numbing dread, burial garment in which a corpse is wrapped, hanging cloth used as a blind (especially for a window','PALL'),
 ('Verb','become less interesting or attractive, cause to lose courage, cover with a pall, cause surfeit through excess though initially pleasing, cause to become flat, lose sparkle or bouquet, lose strength or effectiveness; become or appear boring, insipid, or tiresome (to, lose interest or become bored with something or somebody','PALL'),
 ('Noun','a radioactive metallic element that is similar to tellurium and bismuth; occurs in uranium ores but can be produced by bombarding bismuth with neutrons in a nuclear reactor, a noncommissioned officer in the Navy or Coast Guard with a rank comparable to sergeant in the Army, a European river; flows into the Adriatic Sea, an independent agency of the federal government responsible for mail delivery (and sometimes telecommunications','PO'),
 ('Noun','the molding around a door or window, the lowest part of an entablature; rests immediately on the capitals of the columns','ARCHITRAVE'),
 ('Noun','an act of plundering and pillaging and marauding, (usually plural','DEPREDATION'),
 ('Adjective','(chemistry, physics, biology, liable to change','LABILE'),
 ('Adjective','humorless and disapproving','PO-FACED'),
 ('Noun','a geographical region of northeastern South America including Guyana and Surinam','GUIANA'),
 ('Noun','crust or layer of hard subsoil encrusted with calcium-carbonate occurring in arid or semiarid regions, nitrate-bearing rock or gravel of the sodium nitrate deposits of Chile and Peru','CALICHE'),
 ('Noun','the state of impairing the quality or reducing the value of something, an additional ingredient that is added by mixing with the base, the act of mixing together','ADMIXTURE'),
 ('Noun','an offspring of a mulatto and a white parent; a person who is one-quarter black','QUADROON'),
 ('Noun','a follower who carries out orders without question, (Greek mythology','MYRMIDON'),
 ('Noun','an ancestor in the direct line','PROGENITOR'),
 ('Noun','a formal expression of praise','PANEGYRIC'),
 ('Adjective','formally expressing praise','PANEGYRIC'),
 ('Noun','a legal right to use and derive profit from property belonging to someone else provided that the property itself is not injured in any way','USUFRUCT'),
 ('Noun','an entire system; used in the phrase `the whole shebang','SHEBANG'),
 ('Noun','a disease caused by deficiency of niacin or tryptophan (or by a defect in the metabolic conversion of tryptophan to niacin','PELLAGRA'),
 ('Noun','parasitic bloodsucking roundworms having hooked mouth parts to fasten to the intestinal wall of human and other hosts, infestation of the intestines by hookworms which enter the body (usually','HOOKWORM'),
 ('Adjective','vigorously passionate','CONCUPISCENT'),
 ('Noun','a male member of a religious order that originally relied solely on alms, a pauper who lives by begging','MENDICANT'),
 ('Adjective','practicing beggary','MENDICANT'),
 ('Noun','an adult female person (as opposed to a man, a female person who plays a significant role (wife or mistress or girlfriend, a human female employed to do housework, women as a class','WOMAN'),
 ('Adjective','very drunk','SQUIFFY'),
 ('Noun','(British informal','FUG'),
 ('Noun','the act of placating and overcoming distrust and animosity, the act of atoning for sin or wrongdoing (especially appeasing a deity','PROPITIATION'),
 ('Noun','hate coupled with disgust, an appeal to some supernatural power to inflict evil on someone or some group, the object of cursing or detestation; that which is execrated','EXECRATION'),
 ('Noun','a pass between mountain peaks','COL'),
 ('Adjective','of no real value','NUGATORY'),
 ('Verb','issue soft noises','SUSURRATE'),
 ('Noun','someone who watches examination candidates to prevent cheating','INVIGILATOR'),
 ('Noun','structure forming the transverse part of a cruciform church; crosses the nave at right angles','TRANSEPT'),
 ('Noun','a public register showing the details of ownership and value of land; made for the purpose of taxation','CADASTRE'),
 ('Noun','a monochrome picture made by using several different shades of the same color','CHIAROSCURO'),
 ('Adjective','having a smooth or slippery quality, characterized by lust','LUBRICIOUS'),
 ('Noun','ancient Hebrew unit of liquid measure = 1.5 gallons','HIN'),
 ('Verb','continue talking, move ahead; travel onward in time or space, follow a procedure or take a course, follow a certain course, continue a certain state, condition, or activity','PROCEED'),
 ('Noun','slender freshwater fishes of Eurasia and Africa resembling catfishes','LOACH'),
 ('Noun','a biography that idealizes or idolizes the person (especially a person who is a saint','HAGIOGRAPHY'),
 ('Noun','a native or resident of Manchester','MANCUNIAN'),
 ('Adjective','of or relating to or characteristic of the English city of Manchester or its residents','MANCUNIAN'),
 ('Noun','the lack of knowledge or education','IGNORANCE'),
 ('Noun','glazed earthenware decorated with opaque colors','FAIENCE'),
 ('Adjective','ostentatiously lofty in style, (of sounds','OROTUND'),
 ('Noun','compensation for a wrong, the act of atoning for sin or wrongdoing (especially appeasing a deity','EXPIATION'),
 ('Noun','a tree with limbs cut back to promote a more bushy growth of foliage, a usually horned animal that has either shed its horns or had them removed','POLLARD'),
 ('Verb','convert into a pollard','POLLARD'),
 ('Noun','merchandise issued for sale or public showing (especially a record or film, the act of liberating someone or something, a process that liberates or discharges something, an announcement distributed to members of the press in order to supplement or replace an oral presentation, "the termination of someones employment (leaving them free to depart", euphemistic expressions for death, a legal document evidencing the discharge of a debt or obligation, a device that when pressed will release part of a mechanism, activity that frees or expresses creative energy or emotion, the act of allowing a fluid to escape, a formal written statement of relinquishment, (music','RELEASE'),
 ('Verb','release, as from ones grip", grant freedom to; free from confinement, let (something, prepare and issue for public distribution or sale, eliminate (a substance, generate and separate from cells or bodily fluids, make (information, part with a possession or right, release (gas or energy, make (assets','RELEASE'),
 ('Noun','a fast sailboat with 3 parallel hulls','TRIMARAN'),
 ('Noun','a unit of length equal to one twelfth of a foot, a rare soft silvery metallic element; occurs in small quantities in sphalerite, a state in midwestern United States','IN'),
 ('Adjective','holding office, directed or bound inward, currently fashionable','IN'),
 ('Adverb','to or toward the inside of','IN'),
 ('Verb','influence or urge by gentle urging, caressing, or flattering','INVEIGLE'),
 ('Noun','a policeman who patrols a given region','PATROLMAN'),
 ('Adjective','relating to or occurring or living in or frequenting the open ocean','PELAGIC'),
 ('Noun','any of several plants of the genus Freesia valued for their one-sided clusters of usually fragrant yellow or white or pink tubular flowers','FREESIA'),
 ('Noun','shad-like North American marine fishes used for fish meal and oil and fertilizer','MENHADEN'),
 ('Noun','foolish gibberish','BLATHERSKITE'),
 ('Noun','a largely agricultural county in central England, an industrial city in Leicestershire in central England; built on the site of a Roman settlement','LEICESTER'),
 ('Noun','wale at the top of the side of boat; topmost planking of a wooden vessel','GUNWALE'),
 ('Noun','fermented Mexican drink from juice of various agave plants especially the maguey','PULQUE'),
 ('Noun','a strap from the back of a saddle passing under the horses tail; prevents saddle from slipping forward','CRUPPER'),
 ('Noun','a native or inhabitant of Friesland or Frisia, a West Germanic language spoken in Friesland in the northwestern Netherlands; a near relative of English','FRISIAN'),
 ('Adjective','of or relating to the people or culture or language of Friesland or Frisia','FRISIAN'),
 ('Noun','(Greek mythology','MNEMOSYNE'),
 ('Noun','a medicine used to relieve pain','ANODYNE'),
 ('Adjective','capable of relieving pain','ANODYNE'),
 ('Verb','have as an attribute, knowledge, or skill, have ownership or possession of, enter into and control, as of emotions or ideas','POSSESS'),
 ('Adverb','despite anything to the contrary (usually preceding a concession, by contrast; on the other hand, to whatever degree or extent, in whatever way or manner','HOWEVER'),
 ('Noun','the philosophical study of being and knowing','METAPHYSICS'),
 ('Noun','action taken in return for an injury or offense','REVENGE'),
 ('Verb','take revenge for a perceived wrong','REVENGE'),
 ('Noun','speaking softly without vibration of the vocal cords, a light noise, like the noise of silk clothing or leaves blowing in the wind','WHISPER'),
 ('Verb','speak softly; in a low voice','WHISPER'),
 ('Noun','an advocate of some ideology','IDEOLOGUE'),
 ('Noun','a flabby softness','FLACCIDITY'),
 ('Noun','the performer in the middle of a minstrel line who engages the others in talk, a person who takes part in a conversation','INTERLOCUTOR'),
 ('Adjective','marked by care and persistent effort','SEDULOUS'),
 ('Noun','any of the Sino-Tibetan languages spoken in China; regarded as dialects of a single language (even though they are mutually unintelligible, a native or inhabitant of Communist China or of Nationalist China','CHINESE'),
 ('Noun','the study of the supernatural, a belief in supernatural powers and the possibility of bringing them under human control','OCCULTISM'),
 ('Adjective','proceeding to a conclusion by reason or argument rather than intuition, (of e.g. speech and writing','DISCURSIVE'),
 ('Noun','a sudden violent entrance; a bursting in, a sudden sharp increase in the relative numbers of a population, a sudden violent spontaneous occurrence (usually of some undesirable condition','IRRUPTION'),
 ('Noun','mollusk with a low conical shell, any of various usually marine gastropods with low conical shells; found clinging to rocks in littoral areas','LIMPET'),
 ('Adverb','by bad luck','ALAS'),
 ('Noun','(chemistry, (psychology, especially a sexual one','SUBLIMATION'),
 ('Noun','the quorum required by Jewish law to be present for public worship (at least ten males over thirteen years of age','MINYAN'),
 ('Adverb','without fear','FEARLESSLY'),
 ('Noun','a person suffering from neurosis','NEUROTIC'),
 ('Adjective','characteristic of or affected by neurosis, affected with emotional disorder','NEUROTIC'),
 ('Noun','steadiness of mind under stress','EQUANIMITY'),
 ('Adjective','poorly stated or described, not clear to the mind, not easily deciphered','UNCLEAR'),
 ('Noun','a framework that supports climbing plants','BOWER'),
 ('Verb','enclose in a bower','BOWER'),
 ('Noun','the Muslim official of a mosque who summons the faithful to prayer from a minaret five times a day','MUEZZIN'),
 ('Noun','a lever that is operated with the foot','TREADLE'),
 ('Verb','tread over, operate (machinery','TREADLE'),
 ('Adjective','of or relating to or practicing casuistry, of or relating to the use of ethical principles to resolve moral problems','CASUISTICAL'),
 ('Noun','Argentinian writer remembered for his short stories (1899-1986','BORGES'),
 ('Noun','a student of Chinese history and language and culture','SINOLOGIST'),
 ('Adjective','lacking in courage and manly strength and resolution; contemptibly fearful','PUSILLANIMOUS'),
 ('Noun','a subordinate deity, in some philosophies the creator of the universe','DEMIURGE'),
 ('Adjective','lofty in style','MAGNILOQUENT'),
 ('Adjective','huge; relating to or characteristic of the imaginary country of Brobdingnag, unusually great in size or amount or degree or especially extent or scope, or immense','BROBDINGNAGIAN'),
 ('Noun','a unit of information equal to 1024 mebibytes or 2^30 (1,073,741,824, a castrated tomcat','GIB'),
 ('Verb','become fixed or established, make hard or harder, become hard or harder, cause to accept or become hardened to; habituate','INDURATE'),
 ('Adjective','emotionally hardened','INDURATE'),
 ('Noun','a noisy or scolding or domineering woman, a large strong and aggressive woman','VIRAGO'),
 ('Adjective','having a projecting lower jaw','PROGNATHOUS'),
 ('Noun','the act of concealing yourself and lying in wait to attack by surprise','AMBUSCADE'),
 ('Verb','wait in hiding to attack','AMBUSCADE'),
 ('Noun','a spirally grooved spindle in a clock that counteracts the diminishing power of the uncoiling mainspring, a colored flare used as a warning signal by trucks and trains, a friction match with a large head that will stay alight in the wind, any igniter that is used to initiate the burning of a propellant','FUSEE'),
 ('Noun','a short selection from the Prophets read on every Sabbath in a Jewish synagogue following a reading from the Torah','HAFTORAH'),
 ('Noun','English organist and composer of church and secular music; was granted a monopoly in music printing with William Byrd (1505-1585, (Judaism','TALLIS'),
 ('Noun','religious texts from Deuteronomy inscribed on parchment and rolled up in a case that is attached to the doorframe of many Jewish households in accordance with Jewish law','MEZUZA'),
 ('Adjective','showing signs of wear and tear, tastelessly showy','TATTY'),
 ('Noun','a crowd especially of ordinary or undistinguished persons or things, an irregular fold in an otherwise even surface (as in cloth','RUCK'),
 ('Verb','become wrinkled or drawn together','RUCK'),
 ('Noun','any of several Old World herbs of the genus Medicago having small flowers and trifoliate compound leaves, a plant of the genus Trifolium, an architectural ornament in the form of three arcs arranged in a circle','TREFOIL'),
 ('Adjective','consisting of or resembling mother-of-pearl, having a play of lustrous rainbow colors, or pearlescent, or opaline','NACREOUS'),
 ('Noun','a major Mexican port on the Gulf of Mexico in the state of Veracruz','VERACRUZ'),
 ('Noun','green foliage, the lush appearance of flourishing vegetation','VERDURE'),
 ('Adjective','lacking spirit or liveliness','LANGUOROUS'),
 ('Noun','a short pithy instructive saying','APOTHEGM'),
 ('Adjective','(British slang','SHAMBOLIC'),
 ('Adjective','having identical alleles at corresponding chromosomal loci','HOMOZYGOUS'),
 ('Adjective','of or relating to soteriology','SOTERIOLOGICAL'),
 ('Noun','(anthropology','ETHOS'),
 ('Noun','the act of calling down a curse that invokes evil (and usually serves as an insult','MALEDICTION'),
 ('Adjective','tending to vanish like vapor','EVANESCENT'),
 ('Noun','any system of principles or beliefs','CREDO'),
 ('Noun','the divine word of God; the second person in the Trinity (incarnate in Jesus','LOGOS'),
 ('Noun','Indian physicist who with Albert Einstein proposed statistical laws based on the indistinguishability of particles; led to the description of fundamental particles that later came to be known as bosons','BOSE'),
 ('Noun','a very intense and uncontrolled fire','CONFLAGRATION'),
 ('Noun','clock that measures time by the escape of water','CLEPSYDRA'),
 ('Noun','the event of fading and gradually vanishing from sight','EVANESCENCE'),
 ('Noun','a manuscript (usually written on papyrus or parchment','PALIMPSEST'),
 ('Noun','the formal act of freeing from slavery','MANUMISSION'),
 ('Noun','a quality that arouses emotions (especially pity or sorrow, a feeling of sympathy and sorrow for the misfortunes of others, a style that has the power to evoke feelings','PATHOS'),
 ('Noun','a variation in circumstances or fortune at different times in your life or in the development of something, mutability in life or nature (especially successive alternation from one condition to another','VICISSITUDE'),
 ('Adverb','of the period before the Common Era; preferred by some writers who are not Christians','BCE'),
 ('Adjective','expressing or manifesting praise or approval','APPROBATORY'),
 ('Noun','an event that occurs when something passes from one state or phase to another, a relational difference between states; especially between states before and after some event, the action of changing something, the result of alteration or modification, the balance of money received when the amount you tender is greater than the amount due, a thing that is different, a different or fresh set of clothes, coins of small denomination regarded collectively, money received in return for its equivalent in a larger denomination or a different currency, a difference that is usually pleasant','CHANGE'),
 ('Verb','cause to change; make different; cause a transformation, "undergo a change; become different in essence; losing ones or its original nature", "become different in some particular way, without permanently losing ones or its former characteristics or essence", lay aside, abandon, or leave for another, change clothes; put on different clothes, exchange or replace with another, usually of the same kind or category, give to, and receive from, one another, change from one vehicle or transportation line to another, become deeper in tone, remove or replace the coverings of','CHANGE'),
 ('Noun','gunfire directed along the length rather than the breadth of a formation','ENFILADE'),
 ('Verb','rake or be in a position to rake with gunfire in a lengthwise direction','ENFILADE'),
 ('Noun','a monetary standard under which the basic unit of currency is defined by stated amounts of two metals (usually gold and silver','BIMETALLISM'),
 ('Noun','an outer adjacent area of any place','PURLIEU'),
 ('Noun','either end of the yard of a square-rigged ship','YARDARM'),
 ('Noun','an edge tool used to cut and shape wood','ADZE'),
 ('Noun','a cocktail made of gin or vodka and lime juice, hand tool for boring holes','GIMLET'),
 ('Verb','prepare oneself for a military confrontation, put a girdle on or around, bind with something round or circular','GIRT'),
 ('Adjective','foolishly fond of or submissive to your wife','UXORIOUS'),
 ('Noun','a long wandering and eventful journey, a Greek epic poem (attributed to Homer','ODYSSEY'),
 ('Noun','(Greek mythology, with the help of Athena and Hermes, a conspicuous constellation in the northern hemisphere; between Auriga and Cassiopeia and crossed by the Milky Way','PERSEUS'),
 ('Noun','(Greek mythology','CLYTEMNESTRA'),
 ('Noun','(classical mythology','HERACLES'),
 ('Noun','a wide (ornamented','BALDRIC'),
 ('Noun','a great sacrifice; an ancient Greek or Roman sacrifice of 100 oxen','HECATOMB'),
 ('Noun','an area wholly or partly surrounded by walls or buildings','COURTYARD'),
 ('Noun','any of various chiefly Mediterranean plants of the genera Asphodeline and Asphodelus having linear leaves and racemes of white or pink or yellow flowers','ASPHODEL'),
 ('Adverb','only a very short time before, almost not, by a little','BARELY'),
 ('Noun','intense and continuous artillery fire','CANNONADE'),
 ('Verb','attack with cannons or artillery','CANNONADE'),
 ('Noun','a member of the Uniat Church','UNIATE'),
 ('Adjective','of or relating to former Eastern Christian or Orthodox churches that have been received under the jurisdiction of the Church of Rome but retain their own rituals and practices and canon law','UNIATE'),
 ('Noun','marriage within ones own tribe or group as required by custom or law','ENDOGAMY'),
 ('Adjective','indistinct or hazy in outline, confused and vague; used especially of thinking','MUZZY'),
 ('Adjective','characterized by intense emotion','PERFERVID'),
 ('Noun','the act of predicting (as by reasoning about the future, a statement made about the future','PREDICTION'),
 ('Verb','take exception to','GAINSAY'),
 ('Noun','a long and mournful complaint','JEREMIAD'),
 ('Verb','move (a baby','DANDLE'),
 ('Noun','impassioned appeals to the prejudices and emotions of the populace','DEMAGOGUERY'),
 ('Noun','the trait of spending extravagantly, dissolute indulgence in sensual pleasure','PROFLIGACY'),
 ('Verb','subsist on a meager allowance, supply sparingly and with restricted quantities','STINT'),
 ('Verb','tell or spread rumors','BRUIT'),
 ('Noun','(British slang','BOFFIN'),
 ('Noun','opposition to the flow of electric current resulting from inductance and capacitance (rather than resistance','REACTANCE'),
 ('Noun','the time of day immediately following sunset','GLOAMING'),
 ('Adjective','capable of being attained or accomplished','ATTAINABLE'),
 ('Noun','Ordinary people or the collective mob','CLAMJAMFRY'),
 ('Noun','sloth, laziness or indifference in religious matters','ACCIDIE'),
 ('Noun','Arabian Mythology.  a powerful evil demon or monster.','AFREET'),
 ('Noun','a type of brandy made in Spain and Portugal.','AGUARDIENTE'),
 ('Noun','the letter H, h.','AITCH'),
 ('Noun','(philosophy) weakness of will; acting in a way contrary to one''s sincerely held moral values','AKRASIA'),
 ('Noun','the nickname given to the area centered on Exhibition Road in London, named after Prince Albert, spouse of Queen Victoria. It contains a large number of educational and cultural sites.','ALBERTOPOLIS'),
 ('Noun','an explosive mixture of ammonium nitrate and TNT.','AMATOL'),
 ('Noun','a member of one of the principal tribes, or nations, of Canaan before its conquest by the Israelites. II Sam. 12:26–31; the Semitic language of the Amorites.','AMORITE'),
 ('Adjective','having the shape or form of an eel.','ANGUILLIFORM'),
 ('Adjective','year of wonders; wonderful year.','ANNUS MIRABILIS'),
 ('Noun','a hasty glance; a glimpse; an immediate estimate or judgment; understanding; insight; an outline or summary.','APERACU'),
 ('Noun','Northern U.S. a rustic; a farm laborer, especially a fruit picker.','APPLE-KNOCKER'),
 ('Adjective','characterized by shrewdness, acuteness, or sagacity an argute critic; shrill -- a rich but too argute guitar; sharply serrate','ARGUTE'),
 ('Noun','a mountain gazelle of Arabia, Gazella gazella arabica : almost extinct.','ARIEL'),
 ('Adjective','a brush or instrument for sprinkling holy water; aspersorium','ASPERGILLUM'),
 ('Noun','an erosional scar on the earth''s surface, produced by the impact of a cosmic body, as a meteorite or asteroid.  (crater)','ASTROBLEME'),
 ('Noun','medieval Andalusian Arab polymath.','AVERROES'),
 ('Noun','dry, delicate wit','ATTIC-SALT'),
 ('Noun','a piece sung or played outdoors at dawn, usually as a compliment to someone.','AUBADE'),
 ('Noun','the public declaration of the judgment passed on persons tried in the courts of the the Spanish Inquisition, followed by the execution by the civil authorities of the sentences imposed, especially the burning of condemned heretics at the stake.','AUTO-DA-FE'),
 ('Noun','a hooligan','BADMASH'),
 ('Noun','a mucilaginous preparation made from quince seeds and used for smoothing, glossing, or waving the hair.','BANDOLINE'),
 ('Noun','a member of a noble Persian family of Baghdad who, according to a tale in The Arabian Nights'' Entertainments, gave a beggar a pretended feast with empty dishes.','BARMECIDE'),
 ('Noun','a steep-walled ravine or gorge; a gully with steep sides; arroyo.','BARRANCA'),
 ('Noun','another name for dancehall','BASHMENT'),
 ('Noun','a crevasse, or series of crevasses, at the upper end of a mountain glacier.','BERGSCHRUND'),
 ('Noun','abnormally strong or persistent sexual desire.','EROTOMANIA'),
 ('Noun','a hobo','BINDLESTIFF'),
 ('Noun','a region in Moldavia (Moldova), on the W shore of the Black Sea: formerly in Romania.','BESSARABIAN'),
 ('Noun','a finely tempered sword.','BILBO'),
 ('Noun','Medicine/Medical - a slender, flexible instrument introduced into passages of the body, especially the urethra, for dilating, examining, medicating, etc; a suppository; a wax candle.','BOUGIE'),
 ('Noun','a Spanish gentleman;Southwestern U.S.:a horseman; a woman''s escort or admirer; cavalier.','CABALLERO'),
 ('Noun','a soft, lightweight, drapable fabric of silk or synthetic fibers, having a semilustrous satin face and a dull back.','CHARMEUSE'),
 ('Noun','any of several Chinese porcelains having a translucent, pale green glaze; any porcelain imitating these; a pale gray-green.','CELADON'),
 ('Noun','extant copies of books produced in the earliest stages (before 1501) of printing from movable type; the earliest stages or first traces of anything','INCUNABULA'),
 ('Noun','one who studies historical data by the use of statistical, often computerized, techniques.','CLIOMETRICIAN'),
 ('Noun','a chain of mountains, usually the principal mountain system or mountain axis of a large landmass.','CORDILLERA'),
 ('Noun','a great band of deeply situated transverse white fibers uniting the two halves of the cerebrum in humans and other mammals.','CORPUS CALLOSUM'),
 ('Noun','a game in which one person or side must find a rhyme to a word or a line of verse given by another; inferior rhyme.','CRAMBO'),
 ('Adjective','Appearing legitimate but actually being spurious : These citations are indeed cromulent. [a word used by the schoolteacher, Miss Hoover, in an episode of The Simpsons, in which she defended one made-up word by making up another','CROMULENT'),
 ('Noun','an inordinately wild fight or contentious dispute; brawl; free-for-all.','DONNYBROOK'),
 ('Noun','official approval'', ''official recognition or approval','APPROBATION'),
 ('Adjective','marked by care and persistent effort','ASSIDUOUS'),
 ('Noun','extreme greed for material wealth','CUPIDITY'),
 ('Noun','an acute insufficiency'', ''an insufficient quantity or number','DEARTH'),
 ('Adjective','so thin as to transmit light','DIAPHANOUS'),
 ('Adjective','instructive (especially excessively','DIDACTIC'),
 ('Noun','a song or hymn of mourning composed or performed as a memorial to a dead person','DIRGE'),
 ('Verb','make improvements or corrections to','EMEND'),
 ('Noun','toiletry consisting of any of various substances in the form of a thick liquid that have a soothing and moisturizing effect when applied to the skin','EMOLLIENT'),
 ('Adjective','having a softening or soothing effect especially to the skin','EMOLLIENT'),
 ('Adjective','lofty in style'', ''puffed up with vanity','GRANDILOQUENT'),
 ('Adjective','noisily and stubbornly defiant'', ''boisterously and noisily aggressive','OBSTREPEROUS'),
 ('Noun','a strong liking','PENCHANT'),
 ('Noun','enthusiastic approval','PLAUDIT'),
 ('Adjective','taking on different forms','PROTEAN'),
 ('Adjective','marked by precise accordance with details','PUNCTILIOUS'),
 ('Noun','a blood-red color','SANGUINE'),
 ('Adjective','confidently optimistic and cheerful'', ''inclined to a healthy reddish color often associated with outdoor life','SANGUINE'),
 ('Adjective','slow and apathetic'', ''in a condition of biological rest or suspended animation','TORPID'),
 ('Verb','express criticism towards','UPBRAID'),
 ('Verb','spread negative information about','VITUPERATE'),
 ('Noun','a calculus or concretion found in the stomach or intestines of certain animals, especially ruminants, formerly reputed to be an effective remedy for poison; Obsolete. a counterpoison or antidote.','BEZOAR');
COMMIT;
